library('cummeRbund')
setwd("~/NIHL_M1")
no_noise <- readCufflinks('96_dB_ZO')
csDensity(genes(no_noise))
csScatter(genes(no_noise),'Apical','Basal')
csVolcano(genes(no_noise),'Apical','Basal')
mygene <- getGene(no_noise,'Cacna1h')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Cacna1i')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Cacna1g')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Cacna1c')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Cacna1d')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Cacnb2')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Nrg1')
expressionBarplot(isoforms(mygene))
mygene <- getGene(no_noise,'Neurod1')
expressionBarplot(isoforms(mygene))